[build]
functions = "netlify/functions"

# Force no caching for time API - optimized for AI crawlers
[[headers]]
for = "/.netlify/functions/time"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate, private, max-age=0"
Netlify-CDN-Cache-Control = "no-cache, no-store, must-revalidate"
CDN-Cache-Control = "no-cache, no-store"
Pragma = "no-cache"
Expires = "-1"
X-Robots-Tag = "noarchive, nocache"
Vary = "User-Agent, Accept-Encoding"
X-Cache-Status = "BYPASS"

# Additional cache-busting for any query parameters
[[headers]]
for = "/.netlify/functions/time?*"
[headers.values]
Cache-Control = "no-store, no-cache, must-revalidate"
Pragma = "no-cache"
Expires = "0"
